version: '3.9'

services:
  natttti-pocketbase:
    container_name: natttti-pocketbase
    build: .
    image: natttti-pocketbase:latest
    volumes:
      - natttti-pocketbase-valume:/app/data
    ports:
      - "8090:8090"

volumes:
  natttti-pocketbase-valume:
    name: natttti-pocketbase-valume